In [3]:
import numpy as np
from scipy.optimize import minimize

# Number of possible values of the AI confidence score vector
nj = 3
K = 3
nalpha = nj * K

def objective(alpha, C_H): # Negative log-likelihood
    # alpha = [alpha_11, alpha_21, ..., alpha_K1, alpha_12, alpha_22, ..., alpha_K2, ... alpha_1J, alpha_2J, ..., alpha_KJ]
    current_j = 0
    sum = 0
    for Cs in C_H: # each Cs is an array corresponding to an AI confidence score, where each row is the vector of human confidence scores for a data point
        # Get alphas relevant to this confidence score, i.e. [alpha_1j, alpha_2j, ..., alpha_Kj]
        current_alpha = alpha[(current_j * K):((current_j + 1) * K)]

        # Multiply each row of Cs element-wise by alpha
        sum += np.sum(np.log(np.sum(current_alpha * Cs, axis=1)))

        current_j += 1

    return -1 * sum

def display_result(result):
    # Each column is the distribution over confidence score vectors j given that the correct decision is some particular k
    print(np.round(result.x, 2).reshape(nj, K))

# Form constraints
cons = ()
for i in range(nalpha): # Inequalities: all alpha >= 0
    cons = cons + (({'type':'ineq', 'fun': lambda alpha, i=i: alpha[i]}),)

for k in range(K): # Equalities: all alpha summed over j = 1
    cons = cons + (({'type':'eq', 'fun': lambda alpha, k=k: np.sum(alpha[k::3]) - 1}),)

# Uniform intialization
x0 = np.ones(nalpha) / nj


Example 1: With only one data point per algorithm confidence score, the human uses their confidence scores to 

In [7]:
# Human confidence scores: list of numpy arrays
C_H1 = np.array([[0.3, 0.6, 0.1]])
C_H2 = np.array([[0.8, 0.1, 0.1]])
C_H3 = np.array([[0.1, 0.2, 0.7]])
C_H = [C_H1, C_H2, C_H3]

# Minimize objective 
result = minimize(fun=objective, x0=x0, args=(C_H), constraints=cons)

display_result(result)

[[-0.  1.  0.]
 [ 1. -0. -0.]
 [-0.  0.  1.]]


In [10]:
# Human confidence scores: list of numpy arrays
C_H1 = np.array([[1/3, 1/3, 1/3]])
C_H2 = np.array([[1/3, 1/3, 1/3]])
C_H3 = np.array([[1/3, 1/3, 1/3]])
C_H = [C_H1, C_H2, C_H3]

# Minimize objective 
result = minimize(fun=objective, x0=x0, args=(C_H), constraints=cons)

display_result(result)

[[0.33 0.33 0.33]
 [0.33 0.33 0.33]
 [0.33 0.33 0.33]]


In [ ]:
# Human confidence scores: list of numpy arrays
C_H1 = np.array([[0.3, 0.6, 0.1]])
C_H2 = np.array([[0.1, 0.8, 0.1]])
C_H3 = np.array([[0.1, 0.2, 0.7]])
C_H = [C_H1, C_H2, C_H3]

# Minimize objective 
result = minimize(fun=objective, x0=x0, args=(C_H), constraints=cons)

display_result(result)

In [9]:
# Human confidence scores: list of numpy arrays
C_H1 = np.array([[1/3, 1/3, 1/3]])
C_H2 = np.array([[1/3, 1/3, 1/3]])
C_H3 = np.array([[1/3, 1/3, 1/3]])
C_H = [C_H1, C_H2, C_H3]

# Minimize objective 
result = minimize(fun=objective, x0=x0, args=(C_H), constraints=cons)

display_result(result)

[[0.33 0.33 0.33]
 [0.33 0.33 0.33]
 [0.33 0.33 0.33]]


In [4]:
# Human confidence scores: list of numpy arrays
C_H1 = np.array([[0.3, 0.6, 0.1], [0.7, 0.1, 0.2], [0.1, 0.2, 0.7]])
C_H2 = np.array([[0.8, 0.1, 0.1], [0.6, 0.3, 0.1], [0.6, 0.1, 0.3]])
C_H3 = np.array([[0.1, 0.2, 0.7], [0.2, 0.3, 0.5]])
C_H = [C_H1, C_H2, C_H3]

# Minimize objective 
result = minimize(fun=objective, x0=x0, args=(C_H), constraints=cons)

display_result(result)

In [6]:
# Human confidence scores: list of numpy arrays
C_H1 = np.array([[0.3, 0.6, 0.1]])
C_H2 = np.array([[0.8, 0.1, 0.1]])
C_H3 = np.array([[0.1, 0.2, 0.7]])
C_H = [C_H1, C_H2, C_H3]

# Minimize objective 
result = minimize(fun=objective, x0=x0, args=(C_H), constraints=cons)

display_result(result)

[[-0.  1.  0.]
 [ 1. -0. -0.]
 [-0.  0.  1.]]
